"""empty message

Revision ID: 846d62754e6e
Revises: 1e5178ebab70
Create Date: 2024-08-01 21:41:08.532364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846d62754e6e'
down_revision: Union[str, None] = '1e5178ebab70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('respondee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'topics', 'users', ['respondee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_column('topics', 'respondee_id')
    # ### end Alembic commands ###
