"""Add user identifying params

Revision ID: b70c84fe4276
Revises: ac12df291a1f
Create Date: 2024-08-14 23:46:02.733329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70c84fe4276'
down_revision: Union[str, None] = 'ac12df291a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_agent', sa.String(), nullable=True))
    op.add_column('users', sa.Column('browser', sa.String(), nullable=True))
    op.add_column('users', sa.Column('os', sa.String(), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    op.drop_column('users', 'os')
    op.drop_column('users', 'browser')
    op.drop_column('users', 'user_agent')
    # ### end Alembic commands ###
