"""empty message

Revision ID: cecfc368d2db
Revises: b9a5cbb8272e
Create Date: 2024-08-11 23:41:31.463769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cecfc368d2db'
down_revision: Union[str, None] = 'b9a5cbb8272e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('status', sa.String(), nullable=True))
    op.add_column('topics', sa.Column('chat_id', sa.String(), nullable=True))
    op.drop_column('topics', 'is_active')
    op.add_column('users', sa.Column('minchat_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_minchat_id'), 'users', ['minchat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_minchat_id'), table_name='users')
    op.drop_column('users', 'minchat_id')
    op.add_column('topics', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('topics', 'chat_id')
    op.drop_column('topics', 'status')
    # ### end Alembic commands ###
